version: "3"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  backend:
    build: backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./backend:/app:cached
      - public:/app/public
      - tmp:/app/tmp
      - log:/app/log
    depends_on:
      - db
    ports:
      - 3000:3000
  frontend:
    build: frontend/
    command: /bin/sh -c "yarn install && yarn run dev"
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - backend
volumes:
  public:
  tmp:
  log:
  mysql:
  node_modules:
